### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by LiuC520** [KinsomyJS/location_plugin#1]
It looks like accounts.google.com is having some trouble.
Pub will wait for a while before trying to connect again.

有什么好的办法么？

**Comment by KinsomyJS** [comment]
这是在执行上传命令后报的错误吗，我目前没有遇到过，因为我的网翻墙过了的 @LiuC520

**Comment by LiuC520** [comment]
好吧，我用的是蓝灯翻得墙，好像不行，我在vscode里面执行的命令，android studio需要打开么？需要登陆谷歌账号么？

**Comment by KinsomyJS** [comment]
这些都是不需要的，不管是什么编辑器，写完之后在terminal内执行命令就可以了 
@LiuC520
